"use client";

export const TASK_COPY = {
  en: {
    statuses: {
      SUCCESS: "Success",
      FAILURE: "Failed",
      FAILED: "Failed",
      BLOCKED: "Blocked",
      RUNNING: "Running",
      STARTED: "Running",
      PENDING: "Pending",
      RETRY: "Retrying",
    },
    live: "Live",
    completed: "Task completed successfully",
    failedSummary: "This task did not complete. Review the technical details if investigation is needed.",
    notRecorded: "Not recorded for this task",
    qualityDiagnostics: "Release gate details",
    actualWordCount: "Actual word count",
    allowedWordRange: "Allowed word range",
    headings: "Headings",
    paragraphs: "Paragraphs",
    regenerationAttempted: "Regeneration attempted",
    findings: "Quality findings",
    noFaq: "No FAQ section was detected.",
    seo: "SEO",
    htmlSource: "HTML source",
    markdownSource: "Markdown source",
    seoLoading: "Loading SEO analysis for this article...",
    seoEmpty: "SEO output has not been generated for this article yet.",
    seoError: "SEO analysis could not be loaded.",
    technicalDetails: "Technical details",
    downloadHtml: "Download HTML",
    downloadMarkdown: "Download Markdown source",
    bulkDownloadComplete: (count: number) => `${count} article${count === 1 ? "" : "s"} downloaded.`,
    bulkDownloadPartial: (downloaded: number, omitted: number) =>
      `${downloaded} article${downloaded === 1 ? "" : "s"} downloaded; ${omitted} not included.`,
    bulkDownloadUnavailable: "No completed articles could be retrieved for download.",
    articleTitle: "Article",
    language: "Language",
    keyword: "Keyword",
    generatedAt: "Generated",
    loadingDetail: "Loading article details\u2026",
    gradeExcellent: "Excellent",
    gradeGood: "Good",
    gradeFair: "Fair",
    gradeNeedsWork: "Needs work",
    history: "History",
    revisionHistory: "Revision history",
    noRevisions: "No revisions yet.",
    manualEdit: "Manual edit",
    revisionNote: "Manual edit in Task History",
    viewPastContent: "View previous content",
    unsavedChanges: "Unsaved changes",
    save: "Save",
    editSaved: "Article changes saved.",
    editSaveFailed: "Article changes could not be saved.",
    wordUnit: "words",
  },
  fa: {
    statuses: {
      SUCCESS: "موفق",
      FAILURE: "ناموفق",
      FAILED: "ناموفق",
      BLOCKED: "مسدود",
      RUNNING: "در حال اجرا",
      STARTED: "در حال اجرا",
      PENDING: "در انتظار",
      RETRY: "تلاش مجدد",
    },
    live: "زنده",
    completed: "پردازش با موفقیت کامل شد",
    failedSummary: "این پردازش کامل نشد. در صورت نیاز به بررسی، جزئیات فنی را باز کنید.",
    notRecorded: "برای این پردازش ثبت نشده است",
    qualityDiagnostics: "جزئیات دروازه کیفیت",
    actualWordCount: "تعداد کلمات واقعی",
    allowedWordRange: "بازه مجاز کلمات",
    headings: "تعداد تیترها",
    paragraphs: "تعداد پاراگراف‌ها",
    regenerationAttempted: "تلاش برای تولید دوباره",
    findings: "یافته‌های کیفیت",
    noFaq: "بخش پرسش‌های متداول شناسایی نشد.",
    seo: "سئو",
    htmlSource: "منبع HTML",
    markdownSource: "منبع Markdown",
    seoLoading: "در حال بارگذاری تحلیل سئوی این مقاله...",
    seoEmpty: "هنوز خروجی سئو برای این مقاله تولید نشده است.",
    seoError: "بارگذاری تحلیل سئو ممکن نبود.",
    technicalDetails: "جزئیات فنی",
    downloadHtml: "دانلود HTML",
    downloadMarkdown: "دانلود منبع Markdown",
    bulkDownloadComplete: (count: number) => `${count} مقاله دانلود شد.`,
    bulkDownloadPartial: (downloaded: number, omitted: number) =>
      `${downloaded} مقاله دانلود شد؛ ${omitted} مقاله در فایل قرار نگرفت.`,
    bulkDownloadUnavailable: "هیچ مقاله تکمیل‌شده‌ای برای دانلود دریافت نشد.",
    articleTitle: "مقاله",
    language: "زبان",
    keyword: "کلمه کلیدی",
    generatedAt: "تاریخ تولید",
    loadingDetail: "در حال بارگذاری جزئیات مقاله...",
    gradeExcellent: "عالی",
    gradeGood: "خوب",
    gradeFair: "متوسط",
    gradeNeedsWork: "نیازمند بهبود",
    history: "تاریخچه",
    revisionHistory: "تاریخچه ویرایش‌ها",
    noRevisions: "هنوز ویرایشی ثبت نشده است.",
    manualEdit: "ویرایش دستی",
    revisionNote: "ویرایش دستی در تاریخچه پردازش‌ها",
    viewPastContent: "مشاهده محتوای پیشین",
    unsavedChanges: "تغییرات ذخیره‌نشده",
    save: "ذخیره",
    editSaved: "تغییرات مقاله ذخیره شد.",
    editSaveFailed: "ذخیره تغییرات مقاله ممکن نبود.",
    wordUnit: "کلمه",
  },
  ar: {
    statuses: {
      SUCCESS: "ناجح",
      FAILURE: "فشل",
      FAILED: "فشل",
      BLOCKED: "محظور",
      RUNNING: "قيد التشغيل",
      STARTED: "قيد التشغيل",
      PENDING: "قيد الانتظار",
      RETRY: "إعادة المحاولة",
    },
    live: "مباشر",
    completed: "اكتملت المهمة بنجاح",
    failedSummary: "لم تكتمل هذه المهمة. افتح التفاصيل الفنية عند الحاجة إلى التحقيق.",
    notRecorded: "غير مسجل لهذه المهمة",
    qualityDiagnostics: "تفاصيل بوابة الجودة",
    actualWordCount: "عدد الكلمات الفعلي",
    allowedWordRange: "نطاق الكلمات المسموح",
    headings: "عدد العناوين",
    paragraphs: "عدد الفقرات",
    regenerationAttempted: "تمت محاولة إعادة الإنشاء",
    findings: "نتائج الجودة",
    noFaq: "لم يتم العثور على قسم للأسئلة الشائعة.",
    seo: "تحسين محركات البحث",
    htmlSource: "مصدر HTML",
    markdownSource: "مصدر Markdown",
    seoLoading: "جارٍ تحميل تحليل تحسين البحث لهذه المقالة...",
    seoEmpty: "لم يتم إنشاء مخرجات تحسين البحث لهذه المقالة بعد.",
    seoError: "تعذر تحميل تحليل تحسين البحث.",
    technicalDetails: "التفاصيل التقنية",
    downloadHtml: "تنزيل HTML",
    downloadMarkdown: "تنزيل مصدر Markdown",
    bulkDownloadComplete: (count: number) => `تم تنزيل ${count} مقالة.`,
    bulkDownloadPartial: (downloaded: number, omitted: number) =>
      `تم تنزيل ${downloaded} مقالة؛ لم يتم تضمين ${omitted} مقالة في الملف.`,
    bulkDownloadUnavailable: "تعذر استرداد أي مقالة مكتملة للتنزيل.",
    articleTitle: "المقال",
    language: "اللغة",
    keyword: "الكلمة المفتاحية",
    generatedAt: "تاريخ الإنشاء",
    loadingDetail: "جارٍ تحميل تفاصيل المقال...",
    gradeExcellent: "ممتاز",
    gradeGood: "جيد",
    gradeFair: "متوسط",
    gradeNeedsWork: "يحتاج تحسين",
    history: "السجل",
    revisionHistory: "سجل التعديلات",
    noRevisions: "لم تُسجل أي تعديلات بعد.",
    manualEdit: "تعديل يدوي",
    revisionNote: "تعديل يدوي في سجل المعالجات",
    viewPastContent: "عرض المحتوى السابق",
    unsavedChanges: "تغييرات غير محفوظة",
    save: "حفظ",
    editSaved: "تم حفظ تغييرات المقال.",
    editSaveFailed: "تعذر حفظ تغييرات المقال.",
    wordUnit: "كلمة",
  },
} as const;

export type TaskLocale = keyof typeof TASK_COPY;

export const RISK_COPY = {
  en: {
    title: "Draft Risk",
    low: "Low risk",
    medium: "Needs review",
    high: "High risk",
    blocked: "Blocked",
    loading: "Checking publish risk...",
    blockedPublish: "Publishing is blocked until the critical issue is fixed.",
  },
  fa: {
    title: "ریسک پیش‌نویس",
    low: "ریسک پایین",
    medium: "نیازمند بررسی",
    high: "ریسک بالا",
    blocked: "مسدود",
    loading: "در حال بررسی ریسک انتشار...",
    blockedPublish: "تا رفع مورد بحرانی، انتشار مسدود است.",
  },
  ar: {
    title: "مخاطر المسودة",
    low: "مخاطر منخفضة",
    medium: "يحتاج مراجعة",
    high: "مخاطر عالية",
    blocked: "محظور",
    loading: "جارٍ فحص مخاطر النشر...",
    blockedPublish: "النشر محظور حتى إصلاح المشكلة الحرجة.",
  },
};

export const REVIEW_COPY = {
  en: {
    title: "Review",
    subtitle: "Manager decision before scheduled or public publishing.",
    checklist: "Quality checklist",
    pending_review: "Pending review",
    approved: "Approved",
    changes_requested: "Changes requested",
    rejected: "Rejected",
    approve: "Approve",
    reject: "Reject",
    request_changes: "Request changes",
    noteLabel: "Decision note",
    notePlaceholder: "Add concise feedback for the author or operator.",
    noteRequired: "Feedback is required for this decision.",
    noDecision: "No manager decision yet.",
    reviewedBy: "Reviewed by",
    blockedTitle: "Approval blocked",
    approveBlocked: "Resolve blocking checklist items before approval.",
    liveBlocked: "Public publishing requires manager approval.",
    publishNeedsApproval: "Needs manager approval",
    reviewUpdated: "Review decision saved.",
    reviewError: "Could not update review decision.",
    loading: "Loading review state...",
    unavailable: "Review status is unavailable.",
    checks: {
      title: "Title",
      content: "Article body",
      publish_risk: "Publish risk",
      metadata: "Search metadata",
      keywords: "Keywords",
    },
  },
  fa: {
    title: "بازبینی",
    subtitle: "تصمیم مدیر پیش از زمان‌بندی یا انتشار عمومی.",
    checklist: "چک‌لیست کیفیت",
    pending_review: "در انتظار بازبینی",
    approved: "تأیید شده",
    changes_requested: "نیازمند اصلاح",
    rejected: "رد شده",
    approve: "تأیید",
    reject: "رد",
    request_changes: "درخواست اصلاح",
    noteLabel: "یادداشت تصمیم",
    notePlaceholder: "بازخورد کوتاه برای نویسنده یا اپراتور بنویسید.",
    noteRequired: "برای این تصمیم، بازخورد لازم است.",
    noDecision: "هنوز تصمیم مدیری ثبت نشده است.",
    reviewedBy: "بازبینی توسط",
    blockedTitle: "تأیید مسدود است",
    approveBlocked: "قبل از تأیید، موارد مسدودکننده چک‌لیست را رفع کنید.",
    liveBlocked: "انتشار عمومی نیازمند تأیید مدیر است.",
    publishNeedsApproval: "نیازمند تأیید مدیر",
    reviewUpdated: "تصمیم بازبینی ذخیره شد.",
    reviewError: "امکان ثبت تصمیم بازبینی وجود نداشت.",
    loading: "در حال بارگذاری وضعیت بازبینی...",
    unavailable: "وضعیت بازبینی در دسترس نیست.",
    checks: {
      title: "عنوان",
      content: "متن مقاله",
      publish_risk: "ریسک انتشار",
      metadata: "متادیتای جستجو",
      keywords: "کلمات کلیدی",
    },
  },
  ar: {
    title: "المراجعة",
    subtitle: "قرار المدير قبل الجدولة أو النشر العام.",
    checklist: "قائمة الجودة",
    pending_review: "بانتظار المراجعة",
    approved: "تمت الموافقة",
    changes_requested: "تعديلات مطلوبة",
    rejected: "مرفوض",
    approve: "موافقة",
    reject: "رفض",
    request_changes: "طلب تعديلات",
    noteLabel: "ملاحظة القرار",
    notePlaceholder: "اكتب ملاحظات موجزة للكاتب أو المشغل.",
    noteRequired: "الملاحظات مطلوبة لهذا القرار.",
    noDecision: "لا يوجد قرار إداري بعد.",
    reviewedBy: "راجعه",
    blockedTitle: "الموافقة محظورة",
    approveBlocked: "أصلح عناصر القائمة الحاجبة قبل الموافقة.",
    liveBlocked: "النشر العام يتطلب موافقة المدير.",
    publishNeedsApproval: "يتطلب موافقة المدير",
    reviewUpdated: "تم حفظ قرار المراجعة.",
    reviewError: "تعذر تحديث قرار المراجعة.",
    loading: "جارٍ تحميل حالة المراجعة...",
    unavailable: "حالة المراجعة غير متاحة.",
    checks: {
      title: "العنوان",
      content: "نص المقال",
      publish_risk: "مخاطر النشر",
      metadata: "بيانات البحث",
      keywords: "الكلمات المفتاحية",
    },
  },
};

type ReviewCopy = (typeof REVIEW_COPY)["en"];

export const PUBLISH_COPY = {
  en: {
    wordpressRequired: "WordPress connection required",
    checkingWordPress: "Checking WordPress",
    wordpressBlocked: "Configure WordPress before public publishing.",
    queued: "Publication queued. Waiting for WordPress verification…",
    retrying: "WordPress is temporarily unavailable. Retrying safely…",
    completed: "Published and verified on WordPress.",
    accepted: "Publication is still running in the background. You can safely close this view.",
  },
  fa: {
    wordpressRequired: "اتصال وردپرس لازم است",
    checkingWordPress: "در حال بررسی وردپرس",
    wordpressBlocked: "پیش از انتشار عمومی، وردپرس را متصل کنید.",
    queued: "انتشار در صف قرار گرفت؛ منتظر تأیید وردپرس هستیم…",
    retrying: "وردپرس موقتاً در دسترس نیست؛ تلاش مجدد امن در حال انجام است…",
    completed: "مطلب در وردپرس منتشر و تأیید شد.",
    accepted: "انتشار در پس‌زمینه ادامه دارد و بستن این صفحه امن است.",
  },
  ar: {
    wordpressRequired: "يلزم ربط ووردبريس",
    checkingWordPress: "جارٍ فحص ووردبريس",
    wordpressBlocked: "اربط ووردبريس قبل النشر العام.",
    queued: "تمت إضافة النشر إلى الطابور؛ جارٍ التحقق من ووردبريس…",
    retrying: "ووردبريس غير متاح مؤقتًا؛ تجري إعادة المحاولة بأمان…",
    completed: "تم النشر والتحقق في ووردبريس.",
    accepted: "يستمر النشر في الخلفية ويمكن إغلاق هذه الصفحة بأمان.",
  },
} as const;
