import pytest

from core.exceptions import LLMConnectionError
from infrastructure.llm_client import LLMResponse, ModelProvider, TokenUsage, UnifiedLLMClient


class StubFallbackClient(UnifiedLLMClient):
    def __init__(
        self,
        fail_models: set[str],
        available_providers: set[ModelProvider] | None = None,
    ):
        self.fail_models = fail_models
        self.calls: list[str] = []
        self.available_providers = available_providers or set()
        super().__init__(cache_manager=None, metrics_collector=None)

    def _provider_has_credentials(self, provider: ModelProvider) -> bool:
        return provider in self.available_providers

    async def _call_llm(
        self,
        model: str,
        prompt: str,
        temperature: float,
        max_tokens: int,
        top_p: float,
        stop_sequences: list[str] | None,
    ) -> tuple[str, TokenUsage, str | None]:
        self.calls.append(model)
        if model in self.fail_models:
            raise LLMConnectionError(f"{model} unavailable")
        return f"generated by {model}", TokenUsage(10, 5, 15), "stop"


@pytest.fixture(autouse=True)
def clean_llm_env(monkeypatch):
    for key in (
        "OPENAI_API_KEY",
        "LLM_OPENAI_API_KEY",
        "ANTHROPIC_API_KEY",
        "LLM_ANTHROPIC_API_KEY",
        "LLM_FALLBACK_MODEL",
        "LLM_OPENAI_FALLBACK_MODEL",
        "LLM_ANTHROPIC_FALLBACK_MODEL",
        "LLM_LOCAL_FALLBACK_MODEL",
        "LOCAL_LLM_URL",
    ):
        monkeypatch.delenv(key, raising=False)


@pytest.mark.asyncio
async def test_generate_falls_back_to_available_cross_provider(monkeypatch):
    monkeypatch.setenv("OPENAI_API_KEY", "test-openai-key")
    client = StubFallbackClient(
        fail_models={"claude-haiku-4-5"},
        available_providers={ModelProvider.OPENAI},
    )

    response = await client.generate(
        model="claude-haiku-4-5",
        prompt="Write a launch checklist",
        max_tokens=100,
    )

    assert isinstance(response, LLMResponse)
    assert response.model == "gpt-4o-mini"
    assert response.provider == ModelProvider.OPENAI
    assert response.content == "generated by gpt-4o-mini"
    assert client.calls == ["claude-haiku-4-5", "gpt-4o-mini"]


@pytest.mark.asyncio
async def test_generate_raises_primary_error_when_no_fallback_is_available():
    client = StubFallbackClient(fail_models={"claude-haiku-4-5"})

    with pytest.raises(LLMConnectionError):
        await client.generate(
            model="claude-haiku-4-5",
            prompt="Write a launch checklist",
            max_tokens=100,
        )

    assert client.calls == ["claude-haiku-4-5"]


@pytest.mark.asyncio
async def test_generate_does_not_recursively_fallback_after_fallback_failure(monkeypatch):
    monkeypatch.setenv("OPENAI_API_KEY", "test-openai-key")
    client = StubFallbackClient(
        fail_models={"claude-haiku-4-5", "gpt-4o-mini"},
        available_providers={ModelProvider.OPENAI},
    )

    with pytest.raises(LLMConnectionError):
        await client.generate(
            model="claude-haiku-4-5",
            prompt="Write a launch checklist",
            max_tokens=100,
        )

    assert client.calls == ["claude-haiku-4-5", "gpt-4o-mini"]
